services:
  portfolio:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    container_name: soren_web
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - HOST=0.0.0.0
    networks:
      - soren_network

  # CLI (Soren Mirror)
  soren-cli:
    build:
      context: ./soren-mirror
      dockerfile: Dockerfile
    container_name: soren_cli
    stdin_open: true 
    tty: true        
    environment:  
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DB_HOST=soren_db
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    networks:
      - soren_network

networks:
  soren_network:
    driver: bridge
