services:
  soren_db:
    image: mysql:8.0
    container_name: soren_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - soren_network

# NÚCLEO DE AUTH Y PERSISTENCIA
  soren-core:
    build:
      context: ./soren-core
      dockerfile: Dockerfile
    container_name: soren_api
    ports:
      - "4000:3000" # Exponemos en puerto 4000 para no chocar con el portfolio
    environment:
      - DB_HOST=soren_db
      - DB_USERNAME=${MYSQL_USER}      # Lee 'soren_user' del .env raíz
      - DB_PASSWORD=${MYSQL_PASSWORD}  # Lee tu password larga del .env raíz
      - DB_DATABASE=${MYSQL_DATABASE}  # Lee el nombre de la base de datos del .env raíz
    depends_on:
      - soren_db
    volumes:
      # Montamos el código para desarrollo en vivo (Hot Reload)
      - ./soren-core:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - soren_network
  # CEREBRO (Ollama)
  ollama:
    image: ollama/ollama:latest
    container_name: soren_brain
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./start-ollama.sh:/start-ollama.sh
    entrypoint: ["/bin/bash", "/start-ollama.sh"]
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - soren_network
    restart: on-failure

  # WEB (Portfolio)
  portfolio:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    container_name: soren_web
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - HOST=0.0.0.0
      # Si el portfolio necesita acceder a la DB también:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@soren_db:3306/${MYSQL_DATABASE}
    depends_on:
      - ollama
      - soren_db
    networks:
      - soren_network

  # CLI (Soren Mirror)
  soren-cli:
    build:
      context: ./soren-mirror
      dockerfile: Dockerfile
    container_name: soren_cli
    stdin_open: true 
    tty: true        
    environment:
      - OLLAMA_HOST=http://soren_brain:11434 
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DB_HOST=soren_db
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - ollama
      - soren_db
    networks:
      - soren_network

networks:
  soren_network:
    driver: bridge

volumes:
  ollama_data:
  mysql_data: 